### ISSUE TITLE
Errors when starting

### ISSUE THREAD

**Issue by a-person-01001001** [Stoozy/vimcord#5]
Everytime I start vim with this plugin, it says this in terminal:
```Error
Error detected while processing /Users/mohammadhoque/.vim/plugged/vimcord/plugin/rpc.vim:
line   48:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'psutil'
```

and then in vim it says

```Error
Error detected while processing BufReadPre Autocommands for "*":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
"rpc.vim" 53L, 1489B
Error detected while processing VimEnter Autocommands for "*":
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
NameError: name 'kill' is not defined
Press ENTER or type command to continue
```

**Comment by Stoozy** [comment]
Are you using this on windows?

**Comment by a-person-01001001** [comment]
No, I'm using this on a MacBook.

**Comment by Stoozy** [comment]
can you try manually installing psutil with pip?

**Comment by a-person-01001001** [comment]
I have.

**Comment by Stoozy** [comment]
What's your python and pip version?

**Comment by a-person-01001001** [comment]
Python 3.7.9 and pip 20.2.4. I also have python 3.8

**Comment by a-person-01001001** [comment]
I'm also using `VIM - Vi IMproved 8.2`

**Comment by Stoozy** [comment]
Can you paste the output of `vim --version`

**Comment by a-person-01001001** [comment]
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2020 04:03:24)
macOS version
Included patches: 1-1719
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      -mouse_sysmouse    -tag_old_static
+arabic            +find_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +float             +mouse_xterm       -tcl
+autochdir         +folding           +multi_byte        +termguicolors
-autoservername    -footer            +multi_lang        +terminal
+balloon_eval      +fork()            -mzscheme          +terminfo
+balloon_eval_term +fullscreen        +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +odbeditor         +textprop
+byte_offset       +iconv             +packages          +timers
+channel           +insert_expand     +path_extra        +title
+cindent           +ipv6              +perl/dyn          +toolbar
+clientserver      +job               +persistent_undo   +transparency
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
-farsi             +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -Wshadow -Werror -Wno-error=missing-field-initializers -Wno-error=deprecated-declarations -Wno-error=unused-function
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv /usr/local/lib/libintl.a -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
```

**Comment by Stoozy** [comment]
Weird. Everything seems to be fine. Does psutil work normally? Like can you import psutil on the interactive shell?

**Comment by a-person-01001001** [comment]
Yes, I can import psutil.

**Comment by Stoozy** [comment]
Check if both python versions (3.7.9 and 3.8) allow psutil as import. Then check which version vim is running. Do this in the vim command mode `:python3 import sys` and then run `:python3 print(sys.version)`. Send the output.

**Comment by a-person-01001001** [comment]
```
~ ❯ python3.8
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'psutil'
```
```
~ ❯ python3.7
Python 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> 
```

Vim Version:
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2020 04:03:24)
macOS version`
output of `:python3 print(sys.version)`:
`3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
[Clang 6.0 (clang-600.0.57)]`

**Comment by a-person-01001001** [comment]
I did `python3.8 -m pip3 install psutil` and it seemed to solve the problem.

**Comment by gobborg** [comment]
Will you consider adding "make sure you have psutil installed" to the readme? I had the same issue.
